### ISSUE TITLE
PHP 8.1 features used in code even though the minimum required PHP version for this package is PHP 8.0

### ISSUE THREAD

**Issue by Kaishiyoku** [ryangjchandler/downmark#4]
In the code PHP 8.1 features are being used (new in initializers, enums etc.) even though the minimum required PHP version is PHP 8.0 which doesn't has such features.

**Comment by ryangjchandler** [comment]
@Kaishiyoku Excellent point. Forgot to change this from the package skeleton.

**Comment by ryangjchandler** [comment]
Fixed in v0.0.6.
